### ISSUE TITLE
Timeout error in ranging tag example

### ISSUE THREAD

**Issue by hannobraun** [braun-embedded/rust-dw1000#118]
This happens from time to time:
```
panicked at 'Failed to send ranging request: Timeout', examples/dw1000_ranging_tag.rs:136:13
```

I've observed this in both release and debug mode.

**Comment by hannobraun** [comment]
I can no longer reproduce this and can't find a reason in the code for why this would happen. I'm leaving this be for now. If anyone else sees this or has more information, please post here!

**Comment by jonathanpallant** [comment]
I'm now seeing this:

```
panicked at 'Failed to send ranging request: Timeout', examples\dw1000_ranging_tag.rs:136:13
```

Sometimes rebooting the chip helps.

**Comment by jonathanpallant** [comment]
Also, because of panic-semihosting, if you don't have semihosting enabled in your debugger, you won't know why it has stopped running.

When using J-Link GDB, add "monitor semihosting enable" to the GDB file when you change the port to :2331.

**Comment by hannobraun** [comment]
Thanks for the report, @jonathanpallant! I don't have time to look into it right now (and couldn't reproduce it last time I did), so any help in figuring out why this happens is appreciated.

What's weird about it, is that I've never seen this problem on the anchor. At least I've never experienced that an anchor stops working. So either the anchor is ignoring this error (would be worth checking), or it doesn't happen there.

I've suspected that something is wrong with the timer, not the driver, but when I checked, I didn't find any obvious misuse of the timer, nor was there any indication of bugs in the HAL.

**Comment by hannobraun** [comment]
All examples work as of #145. I'm assuming this issue has been fixed too, whatever it was. There have also been a few updates of the HAL dependency since then.

If it turns out to still exist, we can reopen this issue, or open a new one.
