### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by jkelleyrtp** [braun-embedded/rust-dw1000#144]
Would it be possible to bump the published version so that the GitHub repo and published crates version are in sync?

**Comment by hannobraun** [comment]
Hey @jkelleyrtp, thanks for opening this issue.

I don't want to publish a new version while #140 is completely unaddressed. I haven't found time to address it yet, and don't see that changing soon.

Ideally, someone would fix the examples. But failing that, I would be fine if someone could confirm that the driver itself is working correctly. I don't want to publish a broken release, but without the examples in a working state, I can't confirm that the driver itself is working.

If you have a project using this driver, and can confirm that the latest state from this repository is working, I'd be happy to publish a release.

**Comment by jkelleyrtp** [comment]
I can go through and make sure the examples still work. From what I can tell, no, the ranging examples don't work. I haven't tried any of the other examples (beyond blink). I think #134 might've broken a few things.

**Comment by hannobraun** [comment]
Quite possible, but I actually think the examples were broken before that. Although I might misremember.

Those ranging examples (and to a lesser extent, the other radio examples) have been a huge pain for as long as this project existed. I forgot all the details, but I fixed those a few times; I think mostly because of timing issues.

It's possible that the driver works, but the examples don't. If that were the case, it wouldn't be great, but at least I'd feel comfortable publishing a new release.

**Comment by Kethku** [comment]
Yeah note I wasn't able to get the project working before or after. But I haven't dug into what could be going wrong

**Comment by jkelleyrtp** [comment]
I've verified that these examples do work:
- [x] blink.rs
- [ ] dw1000_delayed_tx.rs
- [ ] dw1000_id.rs
- [x] dw1000_only_rx.rs
- [x] dw1000_only_tx.rs
- [ ] dw1000_ranging_anchor.rs
- [ ] dw1000_ranging_tag.rs
- [ ] dw1000_reg_modify.rs
- [ ] dw1000_reg_rw.rs
- [ ] dw1000_reg_short.rs
- [x] dw1000_rx_tx.rs
- [ ] dw1000_subreg.rs
- [ ] dw1000_subreg_ext_addr.rs
- [ ] lis2dh12.rs
- [ ] uarte.rs
- [ ] uarte_heapless_string.rs

I should have a PR coming soon that upgrades all the dependencies for both crates, moves the examples to defmt, and ensures all the examples work properly.

**Comment by hannobraun** [comment]
Thank you, @jkelleyrtp, this is great work!

**Comment by hannobraun** [comment]
Addressed in #150.
