### ISSUE TITLE
FYI `SYS_STATE` is now available in the datasheet

### ISSUE THREAD

**Issue by korken89** [braun-embedded/rust-dw1000#94]
Hi Hanno!

I just wanted to make you aware that in the latest version of the DW1000 register datasheet the  `SYS_STATE` register is finally specified with all the internal states of the chip.
This could be used to make the low-level driver more complete. :)

BR Emil

**Comment by hannobraun** [comment]
Oh, nice! I'm already using it for some things (don't remember what exactly), based on info I found in some secondary source, but having it properly documented is of course much better :-)

**Comment by korken89** [comment]
Indeed! 
A colleague and I was looking today to start porting our C++ code to Rust and had a look at the DW1000 library and saw this addition in the datasheet. :)
